### ISSUE TITLE
Fiji Plugin Error

### ISSUE THREAD

**Issue by krbarbe3** [Mechanobiology-Lab/BatchDeconvolution#3]
Hi-

I m encountering the following error:

```
Initializing helper readers
Reading additional metadata
Populating metadata
Reading bitmap header
Populating metadata
[WARN] Unknown LaserMedium value 'DAPI' will be stored as "Other"
[WARN] Unknown LaserMedium value 'Alexa Fluor 488' will be stored as "Other"
[WARN] Unknown LaserMedium value 'Cy3' will be stored as "Other"
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: javafx/util/Pair
	at calculations.Split.run(Split.java:128)
	at calculations.Run$1.method(Run.java:115)
	at calculations.Run$1.run(Run.java:58)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

Do you have any suggestions?

Thanks!

Kara

**Comment by ZbigniewBaster** [comment]
Hey Kara,
Just noticed your message. It seems that BioFormats library might have problems with reading your files. What format are your files? you can try initially save them as tiffs - not sure if it help, but tiffs are more native files for ImageJ than other formats. Let me know if you still have this problem. If so, can you test this solution on one file, and if it works, I can prepare a quick macro to transform all the files to tiffs.

Best,
Zbyszek
